#!/bin/bash

docker run \
 -e LANG=C.UTF-8 \
 -e LC_ALL=C.UTF-8 \
 -e TZ=$(cat /etc/timezone) \
 -e DISPLAY=$DISPLAY \
 -e XAUTHORITY=/tmp/.Xauthority \
 -v ${XAUTHORITY}=/tmp/.Xauthority \
 -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
 -h ubuntu-gdal-rasterio \
 --privileged \
 -v ${HOME}:${HOME} \
 -w ${PWD} \
 -v ${PWD}:${PWD} \
 --rm \
 -it \
 gdal-rasterio bash
